### ISSUE TITLE
How about the performance evaluation?

### ISSUE THREAD

**Issue by John1231983** [zhengyang-wang/Unet_3D#1]
Thanks for sharing your work!

I would like to ask you two questions:
1. In your `preprocessing>generate_h5.py`, you have
 ```
       if SUBSTRACT_MEAN:
            inputs -= MEAN
        if NORMALIZE:
            inputs /= 1000.
```
What is value `1000`? Is it maximum intensity? As my knowledge, normalize with zero mean and unit variance must be `(inputs-MEANS)/std`, hence the value `1000` must be standard variance value. Is it right?

2. I am regarding your performance with/without data augment. In my testing, with/without augment data have the same performance. How about you?

**Comment by zhengyang-wang** [comment]
Thanks for being interested in my work.

1.	Yes, the maximum intensity of my data is 1000 (I don’t know what your data is). And you are right about the normalization standard. I already found that my implementation of normalization hurts the performance. The normalization code would be updated in August.

2.	I also got the same problem. But I think if you increase the training patch size, there could be a difference.

**Comment by John1231983** [comment]
Thanks for your reply.
1. Yes. I am using ISeg dataset as you did. From your code, I guess that you normalized the images based on global mean( mean of all image in training or testing set). However, I think it must be the mean of image itself. It means that for eavh image,  we can compute the mean and variance and then do as `image_normalize=(image-image.mean())/image.std())`. Could you try the way and let me know if it is better? 

2. The reason of your augmentation is not good because the brain is symmetric, hence rotation and flip in some ditection are redunant, and making larger search space. I can suggest you use deformation and value augmentation( for each pixel, its value will change in a given range,and followed by gaussian distribution)

**Comment by zhengyang-wang** [comment]
Thank you for your suggestions. I will explore these options and keep you updated.

**Comment by John1231983** [comment]
One more thing you may need to check. If you merge the training and testing set as a set and compute the mean and std value. it may return as follows
```
('new size: ', 0, 159, 9, 191, 61, 217)
[29, 24, 23, 34, 33, 24, 58, 31, 30, 25, 24, 47, 50, 35, 39, 67, 47, 48, 52, 64, 55, 64, 52]
[42, 36, 37, 35, 40, 35, 36, 40, 40, 35, 39, 35, 43, 31, 36, 41, 33, 40, 38, 44, 33, 40, 34]
[45, 37, 35, 53, 52, 38, 89, 47, 47, 39, 37, 72, 76, 55, 61, 103, 73, 74, 80, 99, 85, 99, 89]
[65, 56, 57, 55, 61, 54, 55, 61, 62, 54, 60, 54, 66, 49, 56, 64, 51, 62, 59, 68, 51, 62, 59]
('T1 mean: ', 41.521739130434781)
('T2 mean: ', 37.521739130434781)
('T1 cut mean: ', 64.565217391304344)
('T2 cut mean: ', 58.304347826086953)

```
Then you can use these new sizes to crop the image in each set. However, as you see, the size 159 is out of range of the first image in training set (144x192x256).The reason is the subject 23 has different size 160x192x256, in comparison with other subjects. How to fix it? In that purpose, I will compute the mean and std for whole images in both training and testing set, instead of training set only.

**Comment by zhengyang-wang** [comment]
My data is a bit different. I only have 10 subjects with the same size.

**Comment by John1231983** [comment]
We use same dataset. The last subject is in testing set. You use 10 subjects that are in training set. Instead of this, I used all subjects in both training and testing set. And I found that the last subject in testing set has different size with remaining subject

**Comment by John1231983** [comment]
Have you success to obtain the final result? I am interested in the following questions:
1. Which normalization is good for your dataset? For example: (a) `image_normalize=(image-image.mean())/image.std())` , (b) `image_normalize=(image-image[np.nonzero(image)].mean())/image[np.nonzero(image)].std())` and (c) `image_normalize=MEANS)/1000.0` 

2. Do you see any benefit of data augmentation to your performance? Because brain is symmetric, I guess rotation and flipping will not improve the performance

**Comment by zhengyang-wang** [comment]
1. According to my experiments, (b) is the best.
2. I got the same conclusion with you.

Thank you for your interest in this project. I've been traveling during summer so my reply is delayed. Sorry for that.
