### ISSUE TITLE
Some error and how it fix

### ISSUE THREAD

**Issue by John1231983** [zhengyang-wang/Unet_3D#2]
Thanks for update your work. I try to run your work in my machine and I got some errors and this is how I fix it.

1. `python main.py --action='predict'/'test'` changed to `python main.py --option='predict'/'test'` in ReadMe

2. `from utils.*` in `network.py` , you may get error `ImportError: No module named utils.*`. To fix it, you just add a file `__init__.py` in the folder `utils`. You don't need to put anything into the file.

3. When you perform  `python main.py --option='predict'`. You may get the error about inconsistent shape. `(5x32x32x32x2)` to the target shape `(1x32x32x32x2)` . I did not know how to fix it. :(

4. For generating the hdf5, I think we should you 9 subjects, instead of 10 subject as you did. Because you will use one subject for validation. Hence, the validation subjects should not include in the hdf5 data that used for training.

Thanks!

**Comment by zhengyang-wang** [comment]
Have you tried the latest version? I think 3 is already fixed.

Thanks for pointing out 1.

For 2, your suggestion is indeed a neater way for implementation, but my code should work without any error. Thank you for the suggestion.

For 4, I suggest using cross-validation as we only get 10 subjects.

**Comment by John1231983** [comment]
Yes. I used the newest version that clone yesterday. Could you check it in prediction phase again? For 4, you means you will make hdf5 from 10 subjects then choose one subject for validation. By that way, the tensorflow will know that it just use 9 subjects fro training and another subject for validation. It does not depend on how many subjects that used for generating hdf5. Right?

**Comment by zhengyang-wang** [comment]
I ran several predictions today and there was no problem. Did you change the batch size into 1, like doing testing?

I mean if you want to do cross-validation, you need to train 10 models, each using 9 subjects. That's why I generate h5 file for all 10 subjects. You can choose which one is used for validation and that one will not be used for training. Check the data_reader.py and you will see it. You can set which subject is for validation by just changing the config in main.py. 

Thanks.

**Comment by John1231983** [comment]
Thanks. You are right about the batch size. It should be changed to 1 when testing/prediction. It is running now, but it is too slow (15 mins but didn't complete) in GPU.
For 4, thanks for your information. This is the first time that I use the way. 
For performance, how much Dice performance do you achieve for validation with subject 10? I just ask it to make sure my running is correct.

**Comment by zhengyang-wang** [comment]
The prediction speed depends on the overlap step size. if you set it like 16 or 32, it would be much faster, but (of course) with lower accuracy.

Usually, if the overlap step size is 4, your dice ratio should be higher than 0.8.

Thanks for using my code.

**Comment by John1231983** [comment]
Yes, I am using overlap stepsize as 16. I did not change any setting in your code, except the batch size to 1. It takes about 8 hours (not finish) for prediction. How about you? I am running in gpu

**Comment by zhengyang-wang** [comment]
Usually, if I set the overlap stepsize as 4, it takes about one hour.

Did the screen show "averaging" then "saving"? You may check the result folder and if there is already a result file, it means the program has already finished what it is supposed to do. There might be some problems in numpy.save so that sometimes the program does not end after saving results.

By the way, the "averaging" phase is slow and running in cpu.

**Comment by John1231983** [comment]
this is log that I ran the prediction option. for testing option , it is fast
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:02:00.0
Total memory: 11.90GiB
Free memory: 2.42GiB
2017-08-31 05:12:02.628988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-08-31 05:12:02.629000: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-08-31 05:12:02.629015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
('down ', 0, ' shape ', TensorShape([Dimension(1), Dimension(16), Dimension(16), Dimension(16), Dimension(32)]))
('down ', 1, ' shape ', TensorShape([Dimension(1), Dimension(8), Dimension(8), Dimension(8), Dimension(64)]))
('down ', 2, ' shape ', TensorShape([Dimension(1), Dimension(4), Dimension(4), Dimension(4), Dimension(128)]))
('up ', 2, ' shape ', TensorShape([Dimension(1), Dimension(8), Dimension(8), Dimension(8), Dimension(64)]))
('up ', 1, ' shape ', TensorShape([Dimension(1), Dimension(16), Dimension(16), Dimension(16), Dimension(32)]))
('up ', 0, ' shape ', TensorShape([Dimension(1), Dimension(32), Dimension(32), Dimension(32), Dimension(4)]))
('---->predicting ', 150000)
('--->processing results for: ', (0, 0, 0))
('--->processing results for: ', (0, 0, 16))
('--->processing results for: ', (0, 0, 32))
('--->processing results for: ', (0, 0, 48))
('--->processing results for: ', (0, 0, 64))
('--->processing results for: ', (0, 0, 80))
('--->processing results for: ', (0, 0, 83))
('--->processing results for: ', (0, 16, 0))
('--->processing results for: ', (0, 16, 16))
('--->processing results for: ', (0, 16, 32))
('--->processing results for: ', (0, 16, 48))
('--->processing results for: ', (0, 16, 64))
('--->processing results for: ', (0, 16, 80))
('--->processing results for: ', (0, 16, 83))
('--->processing results for: ', (0, 32, 0))
('--->processing results for: ', (0, 32, 16))
('--->processing results for: ', (0, 32, 32))
('--->processing results for: ', (0, 32, 48))
('--->processing results for: ', (0, 32, 64))
('--->processing results for: ', (0, 32, 80))
('--->processing results for: ', (0, 32, 83))
('--->processing results for: ', (0, 48, 0))
('--->processing results for: ', (0, 48, 16))
('--->processing results for: ', (0, 48, 32))
('--->processing results for: ', (0, 48, 48))
('--->processing results for: ', (0, 48, 64))
('--->processing results for: ', (0, 48, 80))
('--->processing results for: ', (0, 48, 83))
('--->processing results for: ', (0, 64, 0))
('--->processing results for: ', (0, 64, 16))
('--->processing results for: ', (0, 64, 32))
('--->processing results for: ', (0, 64, 48))

**Comment by zhengyang-wang** [comment]
In the end of processing, it will show "averaging" then "saving".

**Comment by John1231983** [comment]
Actually, I spend so much time and it did not complete. So, I cancel it. It ran from yesterday (12hours)

**Comment by zhengyang-wang** [comment]
Here is the end of my log.

--->processing results for:  (96, 119, 72)
--->processing results for:  (96, 119, 76)
--->processing results for:  (96, 119, 80)
--->processing results for:  (96, 119, 83)
--->averaging results
--->saving results
