### ISSUE TITLE
how do i get the dataset

### ISSUE THREAD

**Issue by suntao2012** [zhengyang-wang/Unet_3D#4]
@zhengyang-wang 
I am interested in this repo unet_3d, I'd like to run it, but no input file, I was wondering how can I make a simple dataset, such as generating a random input tensor rather than reading from the file, so that I could run it well?

**Comment by zhengyang-wang** [comment]
Unfortunately, the dataset is not publicly available currently. However, I can tell that the input file is composed of 3D images with 2 channels. The voxel values are integers between 0-1000. The labels are 3D images with one channel and the voxel values are between 0-3 (corresponding to 4 classes). Let me know if you have any other question.
